# Generated by Django 5.2.8 on 2025-11-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='equipos',
            new_name='equipo',
        ),
    ]
