# Generated by Django 5.2.8 on 2025-12-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_equipos_estadisticas_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='amonestaciones',
            new_name='faltas',
        ),
    ]
