# Generated by Django 5.2.8 on 2025-12-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deporte',
            fields=[
                ('iddeporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombredeporte', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=20)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreequipo', models.CharField(max_length=30)),
                ('pertenenciacategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.categoria')),
                ('pertenenciadeporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrejugador', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(max_length=50)),
                ('pertenencia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Resultados.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepartido', models.CharField(max_length=50)),
                ('equipopartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerama', models.CharField(max_length=20)),
                ('pertenencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jj', models.IntegerField()),
                ('jg', models.IntegerField()),
                ('jp', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('gaf', models.IntegerField()),
                ('gc', models.IntegerField()),
                ('dif', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('equipos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Resultados.equipo')),
                ('pertenenciacategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.categoria')),
                ('pertenenciadeporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.deporte')),
                ('pertenenciarama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.rama')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='pertenenciarama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resultados.rama'),
        ),
    ]
