# Generated by Django 5.2.8 on 2025-11-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resultados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='pertenencia',
        ),
        migrations.AddField(
            model_name='jugador',
            name='pertenencia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Resultados.equipo'),
        ),
    ]
