# Generated by Django 5.2.8 on 2025-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resultados', '0002_remove_equipo_pertenencia_jugador_pertenencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='equipos',
            new_name='equipo',
        ),
    ]
