# Generated by Django 5.2.8 on 2025-12-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resultados', '0003_rename_equipos_estadisticas_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='equipo',
            new_name='equipos',
        ),
    ]
