# Generated by Django 5.2.8 on 2025-12-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resultados', '0004_rename_equipo_estadisticas_equipos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='amonestaciones',
            new_name='faltas',
        ),
    ]
