# Generated by Django 5.2.8 on 2025-11-24 00:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_promotor', models.CharField(max_length=100)),
                ('telefono_promotor', models.CharField(max_length=15)),
                ('email_promotor', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/logos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='equipos/comprobantes/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripcion.categoria')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='PagoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.ImageField(upload_to='pagos/comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificando', 'En Verificación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inscripcion.equipo')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('posicion', models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], max_length=20)),
                ('numero_camiseta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/fotos/')),
                ('documento_identidad', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='inscripcion.equipo')),
            ],
            options={
                'ordering': ['numero_camiseta'],
                'unique_together': {('equipo', 'numero_camiseta')},
            },
        ),
    ]
